Fix/missing libssl so
TryQuiet/quiet pull request #1255
Opened 2023-02-24 11:57 UTC by siepra

2023-02-28 09:09 UTC, Kacper-RF requested changes

2023-02-28 09:09 UTC, Kacper-RF commented on packages/e2e-tests/docker/Dockerfile
> +ENV ELECTRON_CUSTOM_VERSION=19.0.5
Please update to 23.0.0

2023-02-28 09:09 UTC, Kacper-RF commented on .github/workflows/e2e-crossplatform.yml
> +        run: curl -LO https://github.com/TryQuiet/quiet/releases/download/quiet%401.0.0-alpha.15/Quiet-1.0.0-alpha.15.AppImage
Might be worth updating the Mac DMG to alpha 15 now to be consistent?

2023-03-02 13:17 UTC, EmiM approved these changes

2023-03-02 13:17 UTC, vinkabuki approved these changes

2023-03-02 13:19 UTC, merged