Secure backend socket.io from other applications that can access localhost i.e. browser
TryQuiet/quiet pull request #1940
Opened 2023-10-09 11:27 UTC by Kacper-RF

…om main.ts to backend and state manager

### Pull Request Checklist

- [ ] I have linked this PR to related GitHub issue.
- [ ] I have updated the CHANGELOG.md file with relevant changes (the file is located at the root of monorepo).

### (Optional) Mobile checklist

Please ensure you completed the following checks if you did any changes to the mobile package:

- [ ] I have run e2e tests for mobile
- [ ] I have updated base screenshots for visual regression tests

2023-10-11 01:45 UTC, leblowl commented on packages/desktop/src/main/main.ts
> +const SOCKET_IO_TOKEN = generateJWT()
Why not just use a random number as a token with basic auth? What benefit does a JWT provide here?

2023-10-18 14:14 UTC, siepra approved these changes
Ideally those utility functions for eg. generating random string should be moved to some external files/classes on mobile (obj-c code is already complex enough to be hard to read).
It will work though

2023-10-25 20:22 UTC, leblowl requested changes
Nice job getting this all working! I have a few suggestions, but looks good overall.

2023-10-25 20:22 UTC, leblowl commented on packages/mobile/ios/Utils.swift
> +}
Same comment as above

> We should probably use something like: https://developer.apple.com/documentation/security/1399291-secrandomcopybytes
>
> and maybe call it `generateSecret` to match other implementations.

Also it looks like this is a duplicate of the same function in AppDelegate.m

2023-11-07 15:32 UTC, leblowl approved these changes
Looks good, thanks!

2023-11-07 15:32 UTC, leblowl commented on packages/backend/src/utils.ts
> +}
I would probably call this file config.ts or options.ts, might make it easier to find

2023-11-09 09:00 UTC, merged