Feature/1836 - Display "<user> has joined <community>" message when unregistered user joins
TryQuiet/quiet pull request #1968
Opened 2023-10-16 08:29 UTC by Kacper-RF

### Pull Request Checklist

- [x] I have linked this PR to related GitHub issue.
- [x] I have updated the CHANGELOG.md file with relevant changes (the file is located at the root of monorepo).

### (Optional) Mobile checklist

Please ensure you completed the following checks if you did any changes to the mobile package:

- [ ] I have run e2e tests for mobile
- [ ] I have updated base screenshots for visual regression tests

### Task Checklist

- [x] desktop
- [x] desktop notification
- [x] helper function in commons
- [x] markdown
- [x] tests for helper
- [x] fix e2e tests

Issue: https://github.com/TryQuiet/quiet/issues/1836
Mobile part will be another PR

We want to send info messages from the user side, we want to do it in a secure way and not trust every informational message from a group of users.

We place specific value in message payload from sender, and we map this value to real info on receivers side.

Updated text
![image](https://github.com/TryQuiet/quiet/assets/111343884/5886f46e-3709-4f98-bc96-89b258ec885e)

2023-10-20 13:11 UTC, holmesworcester requested changes

2023-10-20 13:11 UTC, holmesworcester commented on packages/common/src/transformUserInfoMessages.test.ts
> +        '**@bob** has joined and will be registered soon. 🎉 [Learn more](https://github.com/TryQuiet/quiet/wiki/Quiet-FAQ)',
In cases like this we should point to a particular FAQ entry. I should specify this but if I don't, create a placeholder and link to it. The title can be "How does username registration work?"

2023-10-23 10:38 UTC, EmiM commented on packages/desktop/src/renderer/sagas/notifications/notifications.saga.ts
> +    if (message.type === MessageType.Info && sender !== ownerNickname) {
Why do we try to transform message before even checking notificationsConfig? I think it should be transformed after all initial checks (after `if (!action.payload.isVerified) return`)

2023-10-23 10:44 UTC, EmiM commented on packages/state-manager/src/sagas/socket/startConnection/startConnection.saga.ts
> +      // emit(
?

2023-11-22 11:06 UTC, closed without merging