fix: show context menu on right click #503
TryQuiet/quiet pull request #2355
Opened 2024-03-11 18:35 UTC by agiledev24

![screenshot2](https://github.com/TryQuiet/quiet/assets/80997421/bc9d106b-1907-40b5-aa7b-b7b316254454)
@holmesworcester

2024-03-11 18:58 UTC, leblowl requested changes
Thanks. It looks like there might be one small issue in the package.json file and then could you also update the CHANGELOG when you get a moment (add a new line under [unreleased])?

2024-03-11 18:58 UTC, leblowl commented on packages/desktop/package.json
> +  "version": "2.1.1",
I think we want to keep it as 2.1.2-alpha.9

2024-03-13 13:47 UTC, leblowl commented
@agiledev24 It looks like the check and desktop tests are failing. If we get those passing, I think we can merge this

2025-01-30 21:24 UTC, holmesworcester commented
I'm going to pick this up and try to complete it.

2025-01-30 21:24 UTC, merged