feat: Add in V2 invite links for LFA
TryQuiet/quiet pull request #2661
Opened 2024-11-19 18:06 UTC by islathehut

### Changes

* Updates the V2 invite format to be V1 + LFA
* Refactor invite validation to be more standardized
* Add/update tests

**This is a backwards compatible change.**

### Pull Request Checklist

- [ ] I have linked this PR to a related GitHub issue.
- [ ] I have added a description of the change (and Github issue number, if any) to the root [CHANGELOG.md](https://github.com/TryQuiet/quiet/blob/develop/CHANGELOG.md).

### (Optional) Mobile checklist

Please ensure you completed the following checks if you did any changes to the mobile package:

- [ ] I have run e2e tests for mobile
- [ ] I have updated base screenshots for visual regression tests

2024-11-19 18:06 UTC, islathehut commented
#2627

2024-11-20 17:34 UTC, adrastaea approved these changes

2024-11-20 17:36 UTC, adrastaea requested changes
Everything looks good. Just fix the desktop snapshot test and I'll approve

2024-11-27 16:58 UTC, adrastaea approved these changes

2024-11-27 19:48 UTC, merged