Fix/signature verify in background
TryQuiet/quiet pull request #964
Opened 2022-10-13 01:52 UTC by Dinek007

2022-10-13 12:28 UTC, EmiM commented on packages/backend/src/storage/storage.ts
> +        const signature = stringToArrayBuffer(message.signature)
Looks like this new code is the same as in the event below. It should be at least put into a separate function.

2022-10-13 12:28 UTC, EmiM commented on packages/backend/src/storage/storage.ts
> +          verifyStatus: verify
I think "verified" would be a bit better since it's just a boolean. verifyStatus suggests that there are multiple statuses.

2022-10-13 12:28 UTC, EmiM commented on packages/backend/src/storage/storage.ts
> +      db.events.on('replicate.progress', async (address, _hash, entry, progress, total) => {
I suggest adding tests for those 2 events - verified and unverified message. We already mock some events in test, you can look at "Certificates and peers list are updated on replicated event" unit test.

2022-10-13 12:29 UTC, EmiM commented on packages/backend/src/socket/IOProxy.ts
> +  public loadMessages = (payload: IncomingMessages & {verifyStatus: boolean}) => {
Leftover

2022-10-17 12:22 UTC, vinkabuki requested changes

2022-10-17 12:22 UTC, vinkabuki commented on packages/state-manager/src/sagas/messages/verifyMessage/verifyMessages.saga.ts
> +function* verifyMessage(message: ChannelMessage, verifiedStatus: boolean): Generator {
1. This function doesn't do any verification, so why is it called verify....?
2. It's redundant, because it's only puts actions

2022-10-17 12:22 UTC, vinkabuki commented on packages/state-manager/src/sagas/publicChannels/publicChannels.types.ts
> +  verifiedStatus?: boolean
verifiesStatus: true or verifiedStatus: false is meaningless, it should be isVerified

2022-10-17 12:22 UTC, vinkabuki commented on packages/state-manager/src/sagas/messages/verifyMessage/verifyMessages.saga.ts
> +    yield* spawn(verifyMessage, message, verifiedStatus)
doesn't make any sense, see the comment below

2022-10-17 15:27 UTC, vinkabuki approved these changes

2022-10-18 09:04 UTC, merged